### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by dhritzkiv**

### CODE REVIEW

**Comment by pgilad** [comment]
Can you fix the failing test?

**Comment by wraithgar** [comment]
+1 tests pass for me locally, looks like a travis problem.

Major version, right?

**Comment by dhritzkiv** [comment]
Travis-CI tests are fixed with latest commit

**Comment by cdaringe** [comment]
+1

**Comment by cdaringe** [comment]
will deploy to npm momentarily...

**Comment by cdaringe** [comment]
actually, @lukekarrys or @wraithgar, can you hook it up with publish perms?

**Comment by lukekarrys** [comment]
Done @cdaringe!

**Comment by cdaringe** [comment]
thanks everyone.  published as 4.0.0.  i wasn't 100% sure on major bump, but given that many key deps have undergone many majors, I felt major was a safe bet

**Pull request merged**
