### PR TITLE
Add view and form-view convention tests; typo fix

### LINKED ISSUE #13: Implement view & formField view convention tests
https://github.com/AmpersandJS/ampersand-form-view/issues/28

### PR DESCRIPTION
**Pull request by dhritzkiv**
Easy enough task. I kept the existing tests for things like "init with value" because they test specific conditions of ampersand-array-input-view

Closes #13

### CODE REVIEW

**Comment by dhritzkiv** [comment]
Oops. CI failed as it depends on latest dependencies (addressed in #15)

**Comment by cdaringe** [comment]
dude.  nice!!

**Comment by dhritzkiv** [comment]
Ok, now it runs.

**Comment by kamilogorek** [comment]
All good!

**Comment by cdaringe** [comment]
+1

**Pull request merged**
